#!/bin/bash
# ============================================================
# Email Finder Setup Script
# ============================================================
# This script helps you set up the multi-source email finder
# ============================================================

echo "🔧 Email Finder Setup"
echo "===================="
echo ""

# Install dependencies
echo "📦 Installing Python dependencies..."
pip install -r requirements.txt

echo ""
echo "🔑 API KEY SETUP"
echo "================"
echo ""
echo "To get the best results, you'll want to set up API keys."
echo "Each service has a free tier that should be enough for ~50 contacts."
echo ""
echo "1. HUNTER.IO (recommended - best for professional emails)"
echo "   Sign up: https://hunter.io/users/sign_up"
echo "   Get key: https://hunter.io/api-keys"
echo "   Free tier: 25 searches/month"
echo ""
echo "2. APOLLO.IO (recommended - huge B2B database)"
echo "   Sign up: https://app.apollo.io/#/signup"
echo "   Get key: Settings > Integrations > API Keys"
echo "   Free tier: 50 credits/month"
echo ""
echo "3. ROCKETREACH (good for executives)"
echo "   Sign up: https://rocketreach.co/signup"
echo "   Get key: https://rocketreach.co/api"
echo "   Free tier: 5 lookups/month"
echo ""
echo "4. CLEARBIT (optional - good enrichment)"
echo "   Sign up: https://dashboard.clearbit.com/signup"
echo "   Get key: Dashboard > API"
echo "   Free tier: Limited"
echo ""
echo "============================================================"
echo ""
echo "Once you have your keys, set them as environment variables:"
echo ""
echo "  export HUNTER_API_KEY='your_key_here'"
echo "  export APOLLO_API_KEY='your_key_here'"
echo "  export ROCKETREACH_API_KEY='your_key_here'"
echo "  export CLEARBIT_API_KEY='your_key_here'"
echo ""
echo "Or add them to your ~/.bashrc or ~/.zshrc for persistence."
echo ""
echo "============================================================"
echo ""
echo "📋 USAGE"
echo "========"
echo ""
echo "Basic usage:"
echo "  python email_finder.py -i contacts.csv -o results.csv"
echo ""
echo "With SMTP verification (slower but more accurate):"
echo "  python email_finder.py -i contacts.csv -o results.csv --verify"
echo ""
echo "Process only first 10 contacts:"
echo "  python email_finder.py -i contacts.csv -o results.csv --limit 10"
echo ""
echo "============================================================"
echo ""
echo "✅ Setup complete! Copy your contacts CSV and run the finder."
